### ISSUE TITLE
Ability to use Pico TTS 

### ISSUE THREAD

**Issue by ctmyers** [fritz-fritz/jasper-client#6]
More info here:
http://elinux.org/RPi_Text_to_Speech_(Speech_Synthesis)#Pico_Text_to_Speech
http://www.raspberrypi.org/forums/viewtopic.php?t=68693&p=509289

Its android's TTS engine released under Apache 2 license. It sounds pretty good and works offline (no api key required)

**Comment by fritz-fritz** [comment]
Issue closed as rebasing project off current upstream code base.
