### ISSUE TITLE
Word difficulty

### ISSUE THREAD

**Issue by rickardliljeberg** [fritz-fritz/jasper-client#9]
I have the mic suggested in the project (kinobo) and it all works great with your fork.
I just cannot get it to understand stop, paus and next very well.

It seems they are to short so google seems to mess them up, to change playlists and say previous etc works pretty well but the all important stop and paus does not.

at least "paws" should be added, as I found i often get that, but also longer words for same affect would be good.

Finally, when i manually ran arecord and aplay it was really very noisy. My voice was pretty clear but the background noise was very strong. Any thoughts on that?

**Comment by fritz-fritz** [comment]
Issue closed as rebasing project off current upstream code base.
